{"type":"auditAdvisory","data":{"resolution":{"id":1006767,"path":"swagger-ui-express>swagger-ui-dist","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"3.32.5","paths":["swagger-ui-express>swagger-ui-dist"]}],"metadata":null,"vulnerable_versions":"<4.1.3","module_name":"swagger-ui-dist","severity":"moderate","github_advisory_id":"GHSA-qrmm-w75w-3wpx","cves":[],"access":"public","patched_versions":">=4.1.3","updated":"2021-12-09T17:49:09.000Z","recommendation":"Upgrade to version 4.1.3 or later","cwe":"CWE-918","found_by":null,"deleted":null,"id":1006767,"references":"- https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx\n- https://github.com/swagger-api/swagger-ui/issues/4872\n- https://github.com/swagger-api/swagger-ui/commit/01a3e55960f864a0acf6a8d06e5ddaf6776a7f76\n- https://github.com/advisories/GHSA-qrmm-w75w-3wpx","created":"2021-12-09T20:00:43.811Z","reported_by":null,"title":"Server side request forgery in SwaggerUI","npm_advisory_id":null,"overview":"SwaggerUI supports displaying remote OpenAPI definitions through the `?url` parameter. This enables robust demonstration capabilities on sites like `petstore.swagger.io`, `editor.swagger.io`, and similar sites, where users often want to see what their OpenAPI definitions would look like rendered.\n\nHowever, this functionality may pose a risk for users who host their own SwaggerUI instances. In particular, including remote OpenAPI definitions opens a vector for phishing attacks by abusing the trusted names/domains of self-hosted instances.\n\nAn example scenario abusing this functionality could take the following form:\n- `https://example.com/api-docs` hosts a version of SwaggerUI with `?url=` query parameter enabled.\n- Users will trust the domain `https://example.com` and the contents of the OpenAPI definition.\n- A malicious actor may craft a similar OpenAPI definition and service that responds to the defined APIs at `https://evildomain`.\n- Users mistakenly click a phishing URL like `https://example.com/api-docs?url=https://evildomain/fakeapi.yaml` and enters sensitive data via the \"Try-it-out\" feature.\n\nWe do want to stress that this attack vector is limited to scenarios that actively trick users into divulging sensitive information. The ease of this is highly contextual and, therefore, the threat model may be different for individual users and organizations. It is *not* possible to perform non-interactive attacks (e.g., cross-site scripting or code injection) through this mechanism.\n\n### Resolution \nWe've made the decision to [disable query parameters (#4872)](https://github.com/swagger-api/swagger-ui/issues/4872) by default starting with SwaggerUI version `4.1.3`. Please update to this version when it becomes available (**ETA: 2021 December**). Users will still be able to be re-enable the options at their discretion. We'll continue to enable query parameters on the Swagger demo sites.\n\n### Workaround\nIf you host a version of SwaggerUI and wish to mitigate this issue immediately, you are encouraged to add the following custom plugin code:\n\n```js\nSwaggerUI({\n  //  ...other configuration options,\n  plugins: [function UrlParamDisablePlugin() {\n    return {\n      statePlugins: {\n        spec: {\n          wrapActions: {\n            // Remove the ?url parameter from loading an external OpenAPI definition.\n            updateUrl: (oriAction) => (payload) => {\n              const url = new URL(window.location.href)\n              if (url.searchParams.has('url')) {\n                url.searchParams.delete('url')\n                window.location.replace(url.toString())\n              }\n              return oriAction(payload)\n            }\n          }\n        }\n      }\n    }\n  }],\n})\n```\n\n### Future UX work\n\nThrough the exploration of this issue, it became apparent that users may not be aware to which web server the Try-it-out function will send requests. While this information is currently presented at the top of the page, understanding may improve by displaying it closer to the \"Execute\" button where requests are actually made. We'll be exploring these UX improvements over the coming months and welcome community input. Please create a Feature Request under the GitHub Issue tab to start a conversation with us and the community.","url":"https://github.com/advisories/GHSA-qrmm-w75w-3wpx"}}}
{"type":"auditAdvisory","data":{"resolution":{"id":1006865,"path":"axios>follow-redirects","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"1.14.4","paths":["axios>follow-redirects"]}],"metadata":null,"vulnerable_versions":"<1.14.7","module_name":"follow-redirects","severity":"high","github_advisory_id":"GHSA-74fj-2j2h-c42q","cves":["CVE-2022-0155"],"access":"public","patched_versions":">=1.14.7","updated":"2022-01-11T18:41:09.000Z","recommendation":"Upgrade to version 1.14.7 or later","cwe":"CWE-359","found_by":null,"deleted":null,"id":1006865,"references":"- https://nvd.nist.gov/vuln/detail/CVE-2022-0155\n- https://github.com/follow-redirects/follow-redirects/commit/8b347cbcef7c7b72a6e9be20f5710c17d6163c22\n- https://huntr.dev/bounties/fc524e4b-ebb6-427d-ab67-a64181020406\n- https://github.com/advisories/GHSA-74fj-2j2h-c42q","created":"2022-01-12T23:00:43.967Z","reported_by":null,"title":"Exposure of sensitive information in follow-redirects","npm_advisory_id":null,"overview":"follow-redirects is vulnerable to Exposure of Private Personal Information to an Unauthorized Actor","url":"https://github.com/advisories/GHSA-74fj-2j2h-c42q"}}}
{"type":"auditAdvisory","data":{"resolution":{"id":1006872,"path":"socket.io>engine.io","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"4.1.1","paths":["socket.io>engine.io"]}],"metadata":null,"vulnerable_versions":">=4.0.0 <4.1.2","module_name":"engine.io","severity":"high","github_advisory_id":"GHSA-273r-mgr4-v34f","cves":["CVE-2022-21676"],"access":"public","patched_versions":">=4.1.2","updated":"2022-01-13T16:10:29.000Z","recommendation":"Upgrade to version 4.1.2 or later","cwe":"CWE-754","found_by":null,"deleted":null,"id":1006872,"references":"- https://github.com/socketio/engine.io/security/advisories/GHSA-273r-mgr4-v34f\n- https://nvd.nist.gov/vuln/detail/CVE-2022-21676\n- https://github.com/socketio/engine.io/commit/66f889fc1d966bf5bfa0de1939069153643874ab\n- https://github.com/socketio/engine.io/commit/a70800d7e96da32f6e6622804ef659ebc58659db\n- https://github.com/socketio/engine.io/commit/c0e194d44933bd83bf9a4b126fca68ba7bf5098c\n- https://github.com/socketio/engine.io/releases/tag/4.1.2\n- https://github.com/socketio/engine.io/releases/tag/5.2.1\n- https://github.com/socketio/engine.io/releases/tag/6.1.1\n- https://github.com/advisories/GHSA-273r-mgr4-v34f","created":"2022-01-13T17:00:45.667Z","reported_by":null,"title":"Uncaught Exception in engine.io","npm_advisory_id":null,"overview":"### Impact\n\nA specially crafted HTTP request can trigger an uncaught exception on the Engine.IO server, thus killing the Node.js process.\n\n> RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear\n>   at Receiver.getInfo (/.../node_modules/ws/lib/receiver.js:176:14)\n>   at Receiver.startLoop (/.../node_modules/ws/lib/receiver.js:136:22)\n>   at Receiver._write (/.../node_modules/ws/lib/receiver.js:83:10)\n>   at writeOrBuffer (internal/streams/writable.js:358:12)\n\nThis impacts all the users of the [`engine.io`](https://www.npmjs.com/package/engine.io) package starting from version `4.0.0`, including those who uses depending packages like [`socket.io`](https://www.npmjs.com/package/socket.io).\n\n### Patches\n\nA fix has been released for each major branch:\n\n| Version range | Fixed version |\n| --- | --- |\n| `engine.io@4.x.x` | `4.1.2` |\n| `engine.io@5.x.x` | `5.2.1` |\n| `engine.io@6.x.x` | `6.1.1` |\n\nPrevious versions (`< 4.0.0`) are not impacted.\n\nFor `socket.io` users:\n\n| Version range | `engine.io` version | Needs minor update? |\n| --- | --- | --- |\n| `socket.io@4.4.x` | `~6.1.0` | -\n| `socket.io@4.3.x` | `~6.0.0` | Please upgrade to `socket.io@4.4.x`\n| `socket.io@4.2.x` | `~5.2.0` | -\n| `socket.io@4.1.x` | `~5.1.1` | Please upgrade to `socket.io@4.4.x`\n| `socket.io@4.0.x` | `~5.0.0` | Please upgrade to `socket.io@4.4.x`\n| `socket.io@3.1.x` | `~4.1.0` | -\n| `socket.io@3.0.x` | `~4.0.0` | Please upgrade to `socket.io@3.1.x` or `socket.io@4.4.x` (see [here](https://socket.io/docs/v4/migrating-from-3-x-to-4-0/))\n\nIn most cases, running `npm audit fix` should be sufficient. You can also use  `npm update engine.io --depth=9999`.\n\n### Workarounds\n\nThere is no known workaround except upgrading to a safe version.\n\n### For more information\n\nIf you have any questions or comments about this advisory:\n\n* Open an issue in [`engine.io`](https://github.com/socketio/engine.io)\n\nThanks to Marcus Wejderot from Mevisio for the responsible disclosure.\n","url":"https://github.com/advisories/GHSA-273r-mgr4-v34f"}}}
